### ISSUE TITLE
New Account Welcome Email

### ISSUE THREAD

**Issue by ctorx** [ctorx/brewgr.com#14]
Send a welcome email after an account is created

**Comment by KillaBee2k5** [comment]
I would like to start working on this, what would be the text to include in this message?

**Comment by ctorx** [comment]
Use this:

```
Welcome to Brewgr!

We're glad that you've signed up.  You've just joined a growing community of homebrewers with tons of recipes.  If you haven't already picked a username, you can do so by navigating to:

<https://{IWebSettings.AppRoot}/settings>

If clicking the link above does not work, copy and paste the URL in a new browser window instead.

This is an automatically generated message. Replies are not monitored or answered

Happy Brewing
The Brewgr Team
```

Also, see Brewgr.Web.Email.PasswordResetEmailMessage as a guide ... there is already email infrastructure that will make the task a lot easier.

Thanks!

**Comment by KillaBee2k5** [comment]
Can you close this issue please? And is it possible to make it so I can assign issues to myself so we know who is working on what? Thanks!

**Comment by ctorx** [comment]
The only way you can assign an issue is if you are a collaborator for the repository.  For the time being, we're not adding collaborators as collaborators have the ability to commit directly to the repository.  I'd suggest adding a comment like "I'm working on this" to an issue, or ask me to assign it to myself so others won't work on it.  Thanks for the contributions.

**Comment by KillaBee2k5** [comment]
Ok, no problem!
