### ISSUE TITLE
Add paging to search results

### ISSUE THREAD

**Issue by ctorx** [ctorx/brewgr.com#15]

**Comment by KillaBee2k5** [comment]
I will start working on that.

**Comment by ctorx** [comment]
Great, I will assign this to me so nobody else works on it.

This one is a little tricky because there are multiple tabs that display search results.  Paging ideally, would be done within each tab using AJAX and only pull back the next page of results for that tab alone.

This is open to suggestions if you have other ideas.

**Comment by KillaBee2k5** [comment]
I have been trying a while to add this using the PagedList (http://github.com/TroyGoode/PagedList) library, but I haven't had any luck because of the complexity with the multiple tabs and the partial pages. Would love to hear if you have any other ideas...

**Comment by ctorx** [comment]
Upon looking into this a little further, this project is a bit of a rabbit hole, but definitely achievable.

The biggest challenge I think is the fact that 3 searches execute in parallel (user search, recipe search and blog search).  The results of those queries are packaged into class ``SearchResult`` which has 3 IList properties (one for each search type).

***A "fairly simple" option...***
Change the current Search call in ``DefaultSearchService`` to only fetch a specific number of results for each type (based on a new config setting).  So, any search will only return a max of 10 recipes, 10 users and 10 blog posts, for example.

Next, add 3 new methods to ``DefaultSearchService`` (one for each search type) and rather than returning ``IList<T>`` return ``IPagedList<T>`` (note: ``IPagedList>T>`` is an interface defined in our code -- see it in use in the ``DefaultBeerStyleService`` class line 84)

Then, add a new action on ``SearchController`` that will be used for the AJAX paging -- this would happen after an initial search has rendered results and a user clicks "Next" or "Previous" (look here for how we currently do paging UI: http://brewgr.com/style/american-ipa-recipes)

The new action should take in a search type (i.e. recipe, user, blog), a search term and a page number.  The Search Type determines which of the 3 new methods to call on the ``DefaultSearchService``.  Finally, return json using MVC's ``Json()`` method, and you won't have to worry about different types in the response.

And of course, you will need to utilize jQuery to execute the AJAX calls and format the results accordingly when they come back in the response.  I would do this in a similar fashion to how we do the recipe ingredient rows on the builder -- that is, we use the Qquery template library (called just "t" I think ) to format results -- the template markup should come from an MVC partial which is rendered to the document as an HTML comment -- simply for the purpose of not having to duplicate the markup in client side and server side.

This really is a quite a bit of work with a lot of touch points and I hope this makes sense.

Obviously you don't have to do it this way, but I think it is the simplest.
