### ISSUE TITLE
Mash thickness US to metric conversion in the mash and sparge water calculator is wrong.

### ISSUE THREAD

**Issue by yesbrewnein** [ctorx/brewgr.com#36]
The calculator converts 1 qt/lb to 0.95 l/kg but it should be 2.08 l/kg.

**Comment by ctorx** [comment]
Thanks for the find.

Explanation:
The ratio 1 qt per lb is equal to the ratio .94 l per .45 kg.  You must multiply .45 kg roughly by 2.22 to make it equal to 1.  Multiplying the other side of the ratio (liters) .94 * 2.22 yields roughly 2.08.  The current calculation simply converts the left side of the ratio.
