### ISSUE TITLE
Allow Selection of Color Units

### ISSUE THREAD

**Issue by ctorx** [ctorx/brewgr.com#39]
Allow users to choose between Lovibond, SRM or EBC for color units.

**Comment by KillaBee2k5** [comment]
Why we're almost all the issues closed at once with no check-in?

**Comment by ctorx** [comment]
Hello!

We we're having an issue of people completing tasks without any
discussion.  Most of those tasks were pulled in from our project backlog,
prior to going open source.  So we decided to close anything that wasn't
opened by a user.  If we closed one of yours inadvertently, please let me
know and we can revisit.
