### ISSUE TITLE
Recipe Detail - Change common decimals to fractions

### ISSUE THREAD

**Issue by ctorx** [ctorx/brewgr.com#8]
On Recipe Detail, change common decimals to fractions (i.e. 0.5 = &frac12, 1/4 = &frac14, etc.)

**Comment by rlightner** [comment]
Should this be a configurable option?

**Comment by ctorx** [comment]
I don't think so for now, since we have not yet implemented a general user level preferences feature.  Once that is in place, we can circle back and wrap the implementation with a user preference check.

**Comment by rlightner** [comment]
Should this feature be tabled until user level preferences are implemented?

**Comment by ctorx** [comment]
I would say no.

Wrapping the implementation will be a trivial task and should not hold up
development of this feature.
